### ISSUE TITLE
how to configure the download via rsync

### ISSUE THREAD

**Issue by joelpraxedes** [ChristopheTdn/GOS-LAUNCHER-ARMA3#1]
I found the app amazing, and I liked rsync. I would like to know how to configure FTP for rsync. I just took the Rsync classes to put in my group and download the addons via FTP.

**Comment by ChristopheTdn** [comment]
Well it s pretty complicated for me to explain this to you. My english is poor ;-)
The class Rsync is basec on the cwrsync (https://itefix.net/cwrsync) package. This pack works on windows like Linux. 
So the class call the rsync program.

You have to get a rsync server in front. we use a linux server for that. The IP is hard coded in the application. You can change it of course.

The Gos Launcher search for @GOS directory (the general and after that each category in @GOS -@ISLANDS,@TEMPLATE etc..)
The control who are send to the class routine offer a visual feedback on Gos Launcher interface.

You can find another Gos Launcher base on PYTHON Environnement + QT

It use the same technology but curently in progress. look there : https://github.com/ChristopheTdn/GOSLauncher_A3_Python_version

**Comment by joelpraxedes** [comment]
Yes, so I was going the right way. However, I stopped in the Rsync Server configuration because I do not know where to start configuring.

First, I made the user registration for the server where I placed the folder (LOCAL MODS).

I set the list similar to yours. But at the time of searching for updates it occurs error as if it did not find the Rsync server of our machine.

Progama of yours is Simple and consistent but what is giving me headache is this rsync that I found incredible to download our repository.
I'm grateful that you answered the first question and apologize if I'm being annoying about Rsync.

**Comment by ChristopheTdn** [comment]
well. In the file **fenetrePrincipale.cs** line 1302 to 1335 > you see how the form send information to the class 'GOSLauncherCore.synchroRsyncSpec'

the class **GOSLauncherCore.synchroRsyncSpec** (file **GOSLauncherCore.cs** line **732**) call the **Rsync** clas.; You can see how args are sent to the class.

the class **GOSLauncherCore. synchroRsyncTaille** (file **GOSLauncherCore.cs** line **710**) is only use for updating the size of the download. It use dry function (atttribut '-**vza**')
